-- Seed: 5 perfumes Solution (Black Code, Red Desire, Deep Blue, Yellow Bloom, White Ice)
-- Ejecutar después de la migración de columnas extra.
-- Usa ON CONFLICT (slug) para ser idempotente.

INSERT INTO public.products (
  id,
  slug,
  name,
  description,
  image_url,
  price_retail,
  price_wholesale,
  is_active,
  tagline,
  tipo_de_uso,
  ocasion,
  intensidad,
  perfil_olfativo,
  notas_principales,
  momento_ideal,
  volumen_ml,
  currency,
  sort_order,
  accent_color,
  created_at,
  updated_at
) VALUES
  (
    gen_random_uuid(),
    'black-code',
    'BLACK CODE',
    'Hay presencias que no se anuncian. Se imponen. Black Code nace para el hombre que entra sin hacer ruido y se va dejando marca. La apertura vibrante despierta la atención, el corazón elegante sostiene la mirada y el fondo amaderado profundo construye una identidad firme y segura. Es liderazgo natural. Es ambición silenciosa. Es seguridad que no necesita demostrarse. Black Code no busca aprobación. La genera.',
    'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&q=80',
    28500,
    19950,
    true,
    '',
    'DIA & NOCHE / VERSATIL',
    'FORMAL / ELEGANTE / NEGOCIOS / EVENTOS',
    9,
    'AROMÁTICO / AMADERADO / AFRUTADO / CÍTRICO / ELEGANTE',
    ARRAY['Bergamota', 'manzana', 'grosellas', 'lima', 'pimienta rosa'],
    'DIA & NOCHE / VERSATIL',
    100,
    'ARS',
    1,
    'rgb(0, 255, 255)',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    'red-desire',
    'RED DESIRE',
    'Hay noches que no se explican. Se sienten. Red Desire nace para ese momento exacto en el que la energía cambia. La dulzura inicial envuelve, la lavanda marca carácter y el fondo cálido y ahumado deja una estela que no pasa desapercibida. Es intensidad controlada. Es la cercanía que se vuelve fuego. Es el perfume del hombre que no necesita levantar la voz para dominar la escena. Red Desire no acompaña la noche. La enciende.',
    'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80',
    27200,
    19040,
    true,
    '',
    'NOCHE / CLIMA FRÍO',
    'CITAS / SALIDAS NOCTURNAS / EVENTOS SOCIALES',
    8,
    'ORIENTAL / DULCE / ESPECIADO / AMADERADO / CÁLIDO',
    ARRAY['Castaña', 'azúcar'],
    'NOCHE / CLIMA FRÍO',
    100,
    'ARS',
    2,
    'rgb(255, 0, 100)',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    'deep-blue',
    'DEEP BLUE',
    'Hay espacios donde cada detalle importa. Y cada gesto construye presencia. Deep Blue se abre con una frescura limpia y precisa. Las notas aromáticas aportan claridad, mientras el fondo amaderado sostiene una estela elegante, equilibrada y segura. Es enfoque que se percibe. Es serenidad con carácter. Es el perfume de quien avanza con decisión, sin necesidad de exagerar. Deep Blue no busca impresionar. Inspira confianza.',
    'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=600&q=80',
    26800,
    18760,
    true,
    '',
    'DIA & NOCHE / VERSATIL',
    'OFICINA / REUNIONES / EVENTOS SEMI-FORMALES',
    6,
    'AMADERADO / FRESCO / ELEGANTE / INTENSO',
    ARRAY['Limón', 'pomelo', 'menta', 'pimienta rosa'],
    'DIA & NOCHE / VERSATIL',
    100,
    'ARS',
    3,
    'rgb(0, 150, 255)',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    'yellow-bloom',
    'YELLOW BLOOM',
    'Hay días que se sienten más intensos. Más vivos. Yellow Bloom nace en ese instante donde la energía se expande. La explosión frutal despierta los sentidos, la dulzura envuelve con naturalidad y el fondo cálido deja una estela luminosa que permanece. Es alegría que se vuelve presencia. Es frescura que se transforma en atracción. Es el perfume de quien no teme brillar. Yellow Bloom no sigue la luz. La crea.',
    'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&q=80',
    25900,
    18130,
    true,
    '',
    'NOCHE / PRIMAVERA / VERANO',
    'FIESTAS / EVENTOS SOCIALES / SALIDAS',
    7,
    'FRUTAL / DULCE / AMBARADO / ORIENTAL',
    ARRAY['Naranja siciliana', 'bergamota', 'limón siciliano'],
    'NOCHE / PRIMAVERA / VERANO',
    100,
    'ARS',
    4,
    'rgb(255, 215, 0)',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    'white-ice',
    'WHITE ICE',
    'Hay momentos que no necesitan intensidad. Necesitan claridad. White Ice aparece cuando todo se vuelve liviano. La frescura inicial despierta los sentidos, las notas marinas limpian el aire y el fondo suave y elegante deja una estela pura que transmite calma y seguridad. Es frescura que ordena. Es limpieza que atrae. Es el perfume de quien se siente cómodo siendo auténtico. White Ice no invade. Refresca.',
    'https://images.unsplash.com/photo-1619994121345-5bf2ebf3e267?w=600&q=80',
    27500,
    19250,
    true,
    '',
    'DIA & NOCHE / VERSATIL / CLIMA CÁLIDO',
    'USO DIARIO / TRABAJO / ACTIVIDADES AL AIRE LIBRE',
    5,
    'FRESCO / ACUÁTICO / CÍTRICO / LIMPIO',
    ARRAY['Bergamota', 'lima', 'limón', 'mandarina', 'naranja', 'jazmín'],
    'DIA & NOCHE / VERSATIL / CLIMA CÁLIDO',
    100,
    'ARS',
    5,
    'rgb(200, 200, 255)',
    now(),
    now()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  image_url = EXCLUDED.image_url,
  price_retail = EXCLUDED.price_retail,
  price_wholesale = EXCLUDED.price_wholesale,
  is_active = EXCLUDED.is_active,
  tagline = EXCLUDED.tagline,
  tipo_de_uso = EXCLUDED.tipo_de_uso,
  ocasion = EXCLUDED.ocasion,
  intensidad = EXCLUDED.intensidad,
  perfil_olfativo = EXCLUDED.perfil_olfativo,
  notas_principales = EXCLUDED.notas_principales,
  momento_ideal = EXCLUDED.momento_ideal,
  volumen_ml = EXCLUDED.volumen_ml,
  currency = EXCLUDED.currency,
  sort_order = EXCLUDED.sort_order,
  accent_color = EXCLUDED.accent_color,
  updated_at = now();

-- Asegurar stock inicial por producto (product_stock: product_id, stock, updated_at)
INSERT INTO public.product_stock (product_id, stock, updated_at)
SELECT p.id, 100, now()
FROM public.products p
WHERE p.slug IN ('black-code', 'red-desire', 'deep-blue', 'yellow-bloom', 'white-ice')
ON CONFLICT (product_id) DO UPDATE SET updated_at = now();
