-- Seed: 5 perfumes Solution (Black Code, Red Desire, Deep Blue, Yellow Bloom, White Ice)
-- Ejecutar después de la migración de columnas extra.
-- Usa ON CONFLICT (slug) para ser idempotente.

INSERT INTO public.products (
  id,
  slug,
  name,
  description,
  image_url,
  price_retail,
  price_wholesale,
  is_active,
  tagline,
  tipo_de_uso,
  ocasion,
  intensidad,
  perfil_olfativo,
  notas_principales,
  momento_ideal,
  volumen_ml,
  currency,
  sort_order,
  accent_color,
  created_at,
  updated_at
) VALUES
  (
    gen_random_uuid(),
    'black-code',
    'Black Code',
    'Una fragancia que captura la esencia de la noche urbana. Notas amaderadas y especiadas con un toque de vainilla que perdura hasta el amanecer.',
    'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&q=80',
    28500,
    19950,
    true,
    'Intenso y enigmático para la noche.',
    'Noche / Eventos',
    'Formal / Elegante',
    9,
    'Misterioso, seductor, sofisticado.',
    ARRAY['Lavanda', 'Bergamota', 'Vainilla', 'Ámbar'],
    'Noche. Eventos especiales y citas.',
    100,
    'ARS',
    1,
    'rgb(0, 255, 255)',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    'red-desire',
    'Red Desire',
    'Una explosión de carácter con notas florales y cuero. Para quienes buscan dejar una huella imborrable.',
    'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80',
    27200,
    19040,
    true,
    'Pasión y carácter para quien se atreve.',
    'Día y noche',
    'Versátil',
    8,
    'Apasionado, audaz, memorable.',
    ARRAY['Rosa', 'Azafrán', 'Cuero', 'Musk'],
    'Día y noche. Versátil y con presencia.',
    100,
    'ARS',
    2,
    'rgb(255, 0, 100)',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    'deep-blue',
    'Deep Blue',
    'Inspirado en el océano. Una fragancia que refresca sin perder profundidad, ideal para el uso cotidiano.',
    'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=600&q=80',
    26800,
    18760,
    true,
    'Frescura y profundidad para el día.',
    'Diario',
    'Casual',
    6,
    'Fresco, acuático, limpio.',
    ARRAY['Bergamota', 'Sal marina', 'Maderas blancas', 'Almizcle'],
    'Diario. Oficina y momentos informales.',
    100,
    'ARS',
    3,
    'rgb(0, 150, 255)',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    'yellow-bloom',
    'Yellow Bloom',
    'Notas cítricas y florales que evocan un atardecer de verano. Ligera pero persistente.',
    'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&q=80',
    25900,
    18130,
    true,
    'Energía y optimismo en cada spray.',
    'Casual',
    'Deportes / Vida al aire libre',
    5,
    'Solar, alegre, vibrante.',
    ARRAY['Neroli', 'Jazmín', 'Vainilla', 'Sándalo'],
    'Casual. Deportes y vida al aire libre.',
    100,
    'ARS',
    4,
    'rgb(255, 215, 0)',
    now(),
    now()
  ),
  (
    gen_random_uuid(),
    'white-ice',
    'White Ice',
    'Una fragancia que respira limpieza y sofisticación. Para quienes prefieren lo esencial.',
    'https://images.unsplash.com/photo-1619994121345-5bf2ebf3e267?w=600&q=80',
    27500,
    19250,
    true,
    'Pureza y minimalismo para espíritus modernos.',
    'Diario',
    'Minimalista',
    4,
    'Limpio, minimalista, elegante.',
    ARRAY['Iris', 'Violeta', 'Algodón', 'Musk blanco'],
    'Diario. Minimalista y atemporal.',
    100,
    'ARS',
    5,
    'rgb(200, 200, 255)',
    now(),
    now()
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  image_url = EXCLUDED.image_url,
  price_retail = EXCLUDED.price_retail,
  price_wholesale = EXCLUDED.price_wholesale,
  is_active = EXCLUDED.is_active,
  tagline = EXCLUDED.tagline,
  tipo_de_uso = EXCLUDED.tipo_de_uso,
  ocasion = EXCLUDED.ocasion,
  intensidad = EXCLUDED.intensidad,
  perfil_olfativo = EXCLUDED.perfil_olfativo,
  notas_principales = EXCLUDED.notas_principales,
  momento_ideal = EXCLUDED.momento_ideal,
  volumen_ml = EXCLUDED.volumen_ml,
  currency = EXCLUDED.currency,
  sort_order = EXCLUDED.sort_order,
  accent_color = EXCLUDED.accent_color,
  updated_at = now();

-- Asegurar stock inicial por producto (product_stock: product_id, stock, updated_at)
INSERT INTO public.product_stock (product_id, stock, updated_at)
SELECT p.id, 100, now()
FROM public.products p
WHERE p.slug IN ('black-code', 'red-desire', 'deep-blue', 'yellow-bloom', 'white-ice')
ON CONFLICT (product_id) DO UPDATE SET updated_at = now();
